// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"template/infra/dao"
	"template/service"
)

// Injectors from wire.go:

// Initial service
func InitUserService() *service.UserService {
	iUserDao := dao.NewUserDao()
	userService := service.NewUserService(iUserDao)
	return userService
}
