[app]
name = "Template"
version = "1.0.0"
# run mode: vm|aws_lambda
runmode = "vm"
# environment value: local|dev|test|uat|prod
env.value = "dev"
# prefix of environment variables
env.prefix = "TM_"

[log]
# one of: ERROR, WARN, INFO, DEBUG
level = "INFO"

[cors]
allow.origins = ["https://template.com"]

[http]
# server config
server.port = "8001"

[db]
# database sourece: postgres|mysql|sqlite
sqlite.path = "./data/sqlite.db"
