name: Build and Unit Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Enable manual triggering the actions workflow

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    # container: phcptech/golang-toolmaker:latest ## container doesn't work in ssh mode

    permissions:
      id-token: write   # enable AWS OIDC
      contents: read    # enable checkout github code

    steps:
      # 1. Checkout source code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Show files in workspace
      - name: Show files in workspace
        run: |  
          echo "show directory before build:"
          pwd
          ls -alh 

      # 3. Configure Git safe directory
      - name: Setup a safe directory for git 
        run : |
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      
      # 4. Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.1'

      # 5. Download Go dependencies
      - name: Download Go Modules
        run: |
          go mod download

      # 6. Run unit tests, use short mode to skip long-running tests, e.g. httpserver test and generate coverage report
      - name: Run Unit Tests
        run: |
          GOEXPERIMENT=jsonv2 go vet ./...
          GOEXPERIMENT=jsonv2 go test ./... -coverprofile=coverage.out -covermode=atomic -timeout 60s

      # 7. Build binary
      - name: Build Binary
        run: |
          GOEXPERIMENT=jsonv2 GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
            go build ./...

      # 8. Show build result
      - name: Show build result
        run: |
          echo "show directory after build:"
          pwd
          ls -alh
          